### ISSUE TITLE
Parameter 'true' for Wire.endTransmission() is a stop and not a restart.

### ISSUE THREAD

**Issue by Koepel** [technoblogy/ulisp-msp430#1]
In the file "ulisp-msp430.ino" the function "I2Crestart()" uses a `Wire.endTransmission(true)`. That is a Stop. The parameter needs to be 'false' to omit a Stop and create a Repeated Start.
https://www.arduino.cc/en/Reference/WireEndTransmission

The same code is in the repositories for ARM and ESP8266.

**Comment by technoblogy** [comment]
Sorry for the delay in responding - thanks, I'll incorporate it next release.
